server:
  port: 8080

logging:
  level:
    root: info
    cn.edu.zucc.login.dao: debug

spring:
  jmx:
    default-domain: login
  profiles:
    active: dev

  datasource:
#    url: jdbc:mysql://192.168.52.60:3306/normal?serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/normal?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# ====================MybatisPlus====================
mybatis-plus:
  type-aliases-package: cn.edu.zucc.login.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:/mapper/*Mapper.xml